services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app}
      POSTGRES_DB: ${POSTGRES_DB:-app}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports: ["6379:6379"]

  backend:
    build:
      context: .
      dockerfile: infra/docker/Dockerfile.backend
    env_file: .env
    depends_on: [db, redis]
    ports: ["8000:8000"]

  ingestion:
    build:
      context: .
      dockerfile: infra/docker/Dockerfile.ingestion
    env_file: .env
    depends_on: [db, redis]
    security_opt:
      - seccomp:unconfined
      - no-new-privileges:true
    init: true
    ipc: host
    shm_size: "1gb"
    user: "pwuser"
    environment:
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
      - LOG_LEVEL=DEBUG
    tmpfs:
      - /tmp
      - /home/pwuser/.cache

  ui:
    build:
      context: .
      dockerfile: infra/docker/Dockerfile.ui
    env_file: .env
    depends_on: [backend]
    ports: ["8501:8501"]

volumes:
  dbdata:
